### PR TITLE
Fix build with glibc 2.36

### PR DESCRIPTION
**Pull request by schnitzeltony**
| src/lushlife/lushlife_ui_main.cxx:47:27: error: 'time' was not declared in this scope
|    47 |     srand ((unsigned int) time (NULL));
|       |                           ^~~~
| src/lushlife/lushlife_ui_main.cxx:9:1: note: 'time' is defined in header '<ctime>'; did you forget to '#include <ctime>'?

| src/casynth/casynth_ui_main.cxx:47:27: error: 'time' was not declared in this scope
|    47 |     srand ((unsigned int) time (NULL));
|       |                           ^~~~
| src/casynth/casynth_ui_main.cxx:9:1: note: 'time' is defined in header '<ctime>'; did you forget to '#include <ctime>'?

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by ssj71** [comment]
Thank you.
